version: '3.8'

services:
  n8n-claude:
    build: .
    container_name: n8n-claude-wake
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme123
      - GENERIC_TIMEZONE=Australia/Adelaide
      - TZ=Australia/Adelaide
    volumes:
      - n8n-data:/home/node/.n8n
      - claude-auth:/home/node/.anthropic
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  n8n-data:
    driver: local
  claude-auth:
    driver: local
