[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 600
startCommand = ""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
